/**
 * Report download helpers.
 *
 * Reports are never written to disk without the user naming them first. The
 * flow is deliberately "ask, then generate":
 *
 *   1. chooseSaveTarget() runs SYNCHRONOUSLY from the click handler, while the
 *      browser still considers the gesture active — that is a hard requirement
 *      of window.showSaveFilePicker(). It returns a save target (file handle
 *      and/or filename) or { cancelled: true }.
 *   2. Only if the user did NOT cancel does the caller request the report.
 *   3. writeBlobToTarget() saves the bytes to the chosen location, or falls
 *      back to a normal download using the chosen filename.
 *
 * Cancelling at step 1 means no request is made and nothing is downloaded.
 */

const DEFAULT_EXTENSION = '.pdf'

// Extensions this app produces. deriveFilename strips whichever one a name
// already carries, so a PDF name can be re-pointed at a workbook without the
// old extension surviving in the middle ("Batch.pdf_Report.xlsx").
const KNOWN_EXTENSIONS = ['.pdf', '.xlsx', '.xls', '.csv']

/** True when the browser can offer a real "Save As" dialog. */
export function isSaveFilePickerSupported(win = typeof window !== 'undefined' ? window : undefined) {
  return !!win && typeof win.showSaveFilePicker === 'function'
}

/** Strip characters that are illegal in filenames on Windows/macOS/Linux. */
export function sanitizeFilename(name, { fallback = 'report' } = {}) {
  const cleaned = String(name ?? '')
    // Illegal on at least one major OS. Everything else the user typed
    // (spaces, dashes, dots, underscores) is preserved.
    .replace(/[\\/:*?"<>|]+/g, '_')
    .replace(/\s+/g, ' ')
    .replace(/^\.+/, '')
    .trim()
  return cleaned || fallback
}

/** Keep the correct extension no matter what the user typed. */
export function ensureExtension(name, extension = DEFAULT_EXTENSION) {
  const ext = extension.startsWith('.') ? extension : `.${extension}`
  const base = String(name ?? '').trim()
  if (!base) return ext
  if (base.toLowerCase().endsWith(ext.toLowerCase())) return base
  return `${base.replace(/\.+$/, '')}${ext}`
}

/** Strip a trailing known extension, whichever one the name carries. */
function stripExtension(name) {
  const text = String(name ?? '')
  const lower = text.toLowerCase()
  const hit = KNOWN_EXTENSIONS.find((ext) => lower.endsWith(ext))
  return hit ? text.slice(0, -hit.length) : text
}

/**
 * Build a related filename from one the user chose:
 *   deriveFilename('Batch 12.pdf', 'Inspection')          → 'Batch 12_Inspection.pdf'
 *   deriveFilename('Batch 12.pdf', 'Report', '.xlsx')     → 'Batch 12_Report.xlsx'
 *   deriveFilename('Batch 12.pdf', '', '.xlsx')           → 'Batch 12.xlsx'
 */
export function deriveFilename(filename, suffix, extension = DEFAULT_EXTENSION) {
  const ext = extension.startsWith('.') ? extension : `.${extension}`
  const base = stripExtension(filename)
  const suffixPart = String(suffix ?? '').trim()
  return ensureExtension(`${base}${suffixPart ? `_${suffixPart}` : ''}`, ext)
}

/**
 * Ask the user for a filename (and, where supported, a folder).
 * Returns { cancelled, filename, handle }.
 */
export async function chooseSaveTarget(suggestedName, {
  win = typeof window !== 'undefined' ? window : undefined,
  extension = DEFAULT_EXTENSION,
  description = 'PDF document',
  mimeType = 'application/pdf',
  promptMessage = 'File name for the report',
} = {}) {
  const suggested = ensureExtension(sanitizeFilename(suggestedName), extension)
  const cancelled = { cancelled: true, filename: '', handle: null }
  if (!win) return { cancelled: false, filename: suggested, handle: null }

  if (isSaveFilePickerSupported(win)) {
    try {
      const handle = await win.showSaveFilePicker({
        suggestedName: suggested,
        types: [{ description, accept: { [mimeType]: [extension] } }],
      })
      return {
        cancelled: false,
        filename: ensureExtension(sanitizeFilename(handle?.name || suggested), extension),
        handle: handle || null,
      }
    } catch (err) {
      // The user dismissed the dialog — do not download anything.
      if (err && (err.name === 'AbortError' || err.code === 20)) return cancelled
      // Anything else (insecure context, blocked gesture, unsupported options)
      // falls through to the filename prompt below so the download still works.
    }
  }

  if (typeof win.prompt !== 'function') return { cancelled: false, filename: suggested, handle: null }
  const answer = win.prompt(promptMessage, suggested)
  if (answer === null || answer === undefined) return cancelled // Cancel pressed
  const typed = String(answer).trim()
  return {
    cancelled: false,
    // An empty box means "keep the proposed name" rather than "save as .pdf".
    filename: ensureExtension(sanitizeFilename(typed || suggested), extension),
    handle: null,
  }
}

/**
 * Write the generated bytes to the target the user picked. Returns true when
 * something was actually saved.
 */
export async function writeBlobToTarget(target, blob, {
  win = typeof window !== 'undefined' ? window : undefined,
  doc = typeof document !== 'undefined' ? document : undefined,
} = {}) {
  if (!target || target.cancelled || !blob) return false

  if (target.handle && typeof target.handle.createWritable === 'function') {
    const writable = await target.handle.createWritable()
    await writable.write(blob)
    await writable.close()
    return true
  }

  if (!win || !doc) return false
  const url = win.URL.createObjectURL(blob)
  try {
    const a = doc.createElement('a')
    a.href = url
    a.download = target.filename
    doc.body.appendChild(a)
    a.click()
    a.remove()
  } finally {
    win.URL.revokeObjectURL(url)
  }
  return true
}

/**
 * Convenience wrapper for the simple case: ask, then save an already-fetched
 * blob. Prefer the two-step form when the bytes still need to be generated —
 * asking first is what makes "Cancel" mean "no download".
 */
export async function saveBlobAs(blob, suggestedName, opts = {}) {
  const target = await chooseSaveTarget(suggestedName, opts)
  if (target.cancelled) return false
  return writeBlobToTarget(target, blob, opts)
}
